version = "3.11.1"

runner.dialect = scala3
maxColumn = 110
align.preset = most

newlines.source = keep
newlines.afterCurlyLambdaParams = never
# newlines.afterImplicitKWInVerticalMultiline = true

rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
rewrite.scala3.convertToNewSyntax = true
project.excludeFilters = [".*target/.*", "project/.*", "node_modules/.*"]